#!/bin/bash
# PreToolUse(Edit|Write): block writes to secrets, lockfiles, .git, and generated files.
file_path=$(jq -r '.tool_input.file_path // ""')

case "$file_path" in
  # Committed, secret-free example env files are allowed.
  *.env.example | *.env.sample | *.env.template) : ;;
  # `*.lock` alone does not match package-lock.json — this repo is npm-based, so match the
  # json and yaml forms too or the guard is inert.
  *.env | *.env.* | */.env | */.env.* | *.lock | *lock.json | *lock.yaml | */.git/*)
    echo "Blocked: cannot write to .env files, lockfiles, or the .git directory. To change dependencies run 'npm install' deliberately, then commit the lockfile it produces." >&2
    exit 2
    ;;
esac

# CHANGELOG.md files are generated by changesets from .changeset/*.md entries.
if echo "$file_path" | grep -qE '(^|/)CHANGELOG\.md$'; then
  echo "Blocked: CHANGELOG.md is generated by changesets. Author a changeset instead — 'npm run changeset'." >&2
  exit 2
fi

# next-env.d.ts is regenerated by Next on every dev/build.
if echo "$file_path" | grep -qE 'next-env\.d\.ts$'; then
  echo "Blocked: next-env.d.ts is generated by Next.js. Do not edit it by hand." >&2
  exit 2
fi

exit 0
