services:
  - type: web
    name: micro-image-cache
    runtime: node
    repo: https://github.com/veksen/micro-image.git
    plan: standard
    buildCommand: npm install; npm run build
    startCommand: npm --workspace=micro-image-cache start
    envVars:
      - key: PORT
        value: 9999

  # A static site
  - type: web
    name: docs
    runtime: node
    plan: free
    buildCommand: npm install; npm run build
    startCommand: npm run --workspace=@micro-image/docs start
    envVars:
      - key: PORT
        value: 10000
      - key: NEXT_PUBLIC_DOCS_URL
        value: https://docs-tovg.onrender.com
      - key: NEXT_PUBLIC_IMAGE_PROXY_URL
        value: https://micro-image-cache.onrender.com/cache
